const codes = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  dim: "\x1b[2m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  cyan: "\x1b[36m",
  white: "\x1b[37m",
  magenta: "\x1b[35m",
  black: "\x1b[30m",
  gray: "\x1b[90m",
  redBright: "\x1b[91m",
  greenBright: "\x1b[92m",
  yellowBright: "\x1b[93m",
  blueBright: "\x1b[94m",
  cyanBright: "\x1b[96m",
  whiteBright: "\x1b[97m",
  magentaBright: "\x1b[95m",
};

export const color = {
  red: (text) => `${codes.red}${text}${codes.reset}`,
  green: (text) => `${codes.green}${text}${codes.reset}`,
  yellow: (text) => `${codes.yellow}${text}${codes.reset}`,
  blue: (text) => `${codes.blue}${text}${codes.reset}`,
  cyan: (text) => `${codes.cyan}${text}${codes.reset}`,
  dim: (text) => `${codes.dim}${text}${codes.reset}`,
  reset: (text) => `${codes.reset}${text}${codes.reset}`,
  magenta: (text) => `${codes.magenta}${text}${codes.reset}`,
  black: (text) => `${codes.black}${text}${codes.reset}`,
  gray: (text) => `${codes.gray}${text}${codes.reset}`,
  redBright: (text) => `${codes.redBright}${text}${codes.reset}`,
  greenBright: (text) => `${codes.greenBright}${text}${codes.reset}`,
  yellowBright: (text) => `${codes.yellowBright}${text}${codes.reset}`,
  blueBright: (text) => `${codes.blueBright}${text}${codes.reset}`,
  cyanBright: (text) => `${codes.cyanBright}${text}${codes.reset}`,
  whiteBright: (text) => `${codes.whiteBright}${text}${codes.reset}`,
  magentaBright: (text) => `${codes.magentaBright}${text}${codes.reset}`,
  bright: (text) => `${codes.bright}${text}${codes.reset}`,
};